climatechange-ai/climatechange_ai

Gemfile, Gemfile.lock, _config.yml, _layouts/default.html, assets/css/style.scss, generate_resources_html.rb, resources.md, resources_content.md
With exciting non-exclusive accordion action:
=> Add resources page

assets/css/style.scss, mailing_list.md, newsletter.md
=> Show most recent newsletter on page (and link to archive)

_layouts/default.html, assets/css/style.scss, index.md
=> Add links to forum

assets/css/style.scss
Slight improvement to the UI to make expandability/collapsibility more obvious
=> Improve abstract expand/collapse UI

_layouts/default.html, assets/css/style.scss
The forum has been around for a little while, so this removes the "new!" tag:
=> Remove new! tag

ICLR2020_workshop.md, _layouts/default.html
An extremely simple first-pass improvement that will work out of the box:
=> Distinguish current and past events

ICLR2020_workshop.md, assets/css/style.scss
The user's time zone is computed automatically using the [Luxon](https://moment.github.io/luxon/index.html) library :)
=> ICLR schedule as table with multiple time zones

ICLR2020_workshop.md
A proposal to change buttons and the ordering of content. (Sponsors and organizers are now after accepted works, and sponsors now get a button. To make space, the About button has been removed.)
=> Proposed reorganization of ICLR page

index.md
=> First pass at front-page notice for ICLR workshop

index.md
=> Make last “learn” bullet more concise

about.md, generate_people_html.rb, people.json
This is a much simpler way of listing roles :) 
...
=> Version 3 of role display

_layouts/default.html, assets/css/style.scss
=> Add social media links to footer

events/neurips2020.md
A few minor tweaks to the language in the first half or so.
Added a bit more context to the Impact section.
=> Evan's tweaks to neurips2020.md

events/neurips2020.md
link and consistency fixes, minor wording changes, additional instruction for mentee application
=> fixes and minor changes

events/neurips2020.md
Still need to pick a date and time, set up call-in information.
=> Evan added blurb about webinar to neurips2020.md

events/neurips2020.md
Added strikethrough to submission deadlines and submission URLs for mentorship program.
Removed the announcement about the mentorship program.
Added a period to the end of the announcement about the webinar.
=> Strikethrough mentor deadlines neurips2020.md

events/neurips2020.md
=> Added David R and Lynn to neurips2020.md

webinars.md
=> Move November 23 to past webinars

_data/carousels.yml, _layouts/default.html, events.md, events/happy_hour.md, join/happy_hour.html
Also appears under the events dropdown and on the events page:
=> Initial draft of happy hour page

events/neurips2020.md
=> add calendar subscription info

_data/neurips2020_papers.yml, generate_neurips2020_files.rb
=> Associate all submissions with Slideslive IDs

events/neurips2020.md
Updated registration deadline in announcements and added a missing comma in the first announcement.
=> Updated reg deadline

events/neurips2020.md
Using image/NeurIPS2020_preview_copy2.png
=> Updating og image url

events/neurips2020.md
Saw some cropping issues with #101, this is the ratio of the last uncropped social media img
=> Revert back resizing of image to 850x443

_data/neurips2020_papers.yml, _data/neurips2020_schedule.yml, events/neurips2020.md, generate_neurips2020_files.rb
Add poster session information to papers:
=> Poster sessions

_data/neurips2020_papers.yml, _data/neurips2020_schedule.yml, events/neurips2020.md, generate_neurips2020_files.rb
=> Add spotlights (and store slideslive speakers)

_data/neurips2020_schedule.yml, events/neurips2020.md
Announcements
Schedule header
Sample of bios and more info on how to join
=> flesh out schedule and participation info

events/neurips2020/mingle-bingo-card.md, events/neurips2020/mingle-bingo-winners.md
=> Add mingle bingo card and winners

assets/css/style.scss, events/neurips2020.md, neurips2020-livestream.md
=> First pass at updated livestream page

_data/neurips2020_schedule.yml, events/neurips2020.md
at top
schedule
poster session
=> make participation info clearer

_data/neurips2020_schedule.yml, _data/neurips2020_sideevent_schedule.yml, events/neurips2020.md
@asross I created a new `neurips2020_sidevent_schedule.yml` file for the NeurIPS side event. Not sure if that's the best way to do it. Would this create any bugs in the page?
=> add side-event schedule

_data/carousels.yml, assets/css/style.scss, index.html
Super simple pass at redesigned carousels that are easier to read. Also fixes a mobile issue where the carousel arrows were slightly cut off:
=> Redesign carousels and fix mobile issue

_data/carousels.yml
remove ETH Zurich podcast, add Böll talk
=> update news items on homepage

events/happy_hour.md
Suggested restructuring of happy hour page to make it a bit easier to find info quickly
=> suggested restructuring of happy hour page

events/neurips2021.md
=> Add placeholder page for NeurIPS 2021 submission

events/happy_hour.md
Stating that next happy hour is first Wednesday of July
=> Update happy hour times

about.md
Updated press coverage and divided into articles and podcasts/radio
=> Update press coverage

index.html, newsletter.md
add additional description to newsletter signup, including link to past issues
also clean up wording in "archive" slightly, since there may be more eyes on it
=> details for homepage newsletter signup

index.html
In context of the full page:
EDITED: Current version
=> proposed change to top of homepage, to make CCAI purpose stand out better

papers.html
=> Add authors to workshop paper table <details> to allow author text search

_data/icml2021_papers.yml, _data/icml2021_schedule.yml, events/icml2021.md
(Also slightly tweak the underlying data for easier display)
=> Add poster session to accepted works table

_data/icml2021_schedule.yml, events/icml2021.md, icml2021_livestream.md
Initial modal dialog with signup form (only appears once):
Whole livestream page:
Whole of new main page:
=> Add livestream page similar to NeurIPS 2021

index.html
=> Add banner link to workshop from main page

events/icml2021.md
=> Add local timezone for poster sessions

_data/icml2021_schedule.yml, _data/workshops.yml, events/icml2021.md
(Still need to add individualized slideslive URLs for each event, but my internet is not great right now)
=> Initial pass at archival ICML page

_data/carousels.yml
=> Expand carousels into three categories and add entry for NeurIPS 2021

_data/icml2021_papers.yml, _data/workshops.yml, _layouts/default.html
See: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing
=> Add meta tags for proper workshop paper indexing in Google Scholar

_layouts/paper.html
=> Add citation button

calls/innovation_grants.md
=> faq on eligibility

calls/innovation_grants.md
=> add faq on equity

calls/innovation_grants.md
Last FAQ in timeline and budget
=> Add faq on dataset timeline and overhead calculation

events/cop26.md
=> Link and additional speakers German pavilion

events/happy_hour.md
=> Auto zone handling for happy hours

about.md, press_releases/2021-11-08/release.md
=> GPAI report press release - embargoed till 10am UK time, Nov 8

events/happy_hour.md
Was formerly in EST/GMT+1, which got confusing due to daylight savings.
Still need to update the poster.
=> Switched happy hour times to UTC

_data/neurips2021_schedule.yml, events/neurips2021.md, scripts/generate_neurips2021_schedule.rb
=> Add initial pass at NeurIPS 2021 schedule

index.html
=> Add most recent blog post to featured content carousel

summaries.md
=> Store & load interactive summary filters in URL

_layouts/paper.html
Would fix an issue on https://www.climatechange.ai/papers/neurips2021/8
=> Add MathJax support for paper pages

events/neurips2021.md
=> Embed Circle in neurips workshop page
